# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: tm12_arm
  joint_model_group_pose: start_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_1_joint
    - shoulder_2_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
controller_list:
  - name: tm12_palletizer/tm12_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
